"""Finalize index references to the successful, separately versioned audit."""
from pathlib import Path
p=Path(__file__).resolve().with_name('EVIDENCE_INDEX.md')
s=p.read_text(encoding='utf-8').replace('energy_h1_audit_v1/','energy_h1_audit_v2/')
s=s.replace('Paths resolve from the repository root. Use',
 'Paths resolve from the repository root. The preferred canonical streams are under [energy_h1_audit_v2/canonical_streams](../../smart_building_conformal/outputs/matched_forecasting005/energy_h1_audit_v2/canonical_streams); they explicitly preserve the source Python-None group as the string `None`. The immutable original v1 model streams stored that group as an empty CSV field. Every other column is identical, verified in the [schema mapping](../../smart_building_conformal/outputs/matched_forecasting005/energy_h1_audit_v2/identifier_schema_mapping.csv). Use')
s=s.replace('& C:/cfs_venv/Scripts/python.exe -B -m src.matched_forecasting005 validate --matrix outputs/amendment005/support_design_v1/experiment_matrix.csv --dataset pleia_energy --horizon 1 --outer-fold 0 --model-seed 42 --out outputs/matched_forecasting005/pleia_energy_h1_f0_s42_v1 --receipt outputs/matched_forecasting005/energy_h1_audit_recheck',
 '& C:/cfs_venv/Scripts/python.exe -B scripts/read_matched_energy005.py validate --receipt outputs/matched_forecasting005/energy_h1_audit_recheck')
s=s.replace('& C:/cfs_venv/Scripts/python.exe -B -m src.matched_forecasting005 resume --matrix outputs/amendment005/support_design_v1/experiment_matrix.csv --dataset pleia_energy --horizon 1 --outer-fold 0 --model-seed 42 --out outputs/matched_forecasting005/pleia_energy_h1_f0_s42_v1 --forbid-fits --receipt outputs/matched_forecasting005/validation/energy_h1_resume_recheck.json',
 '& C:/cfs_venv/Scripts/python.exe -B scripts/read_matched_energy005.py resume --receipt outputs/matched_forecasting005/validation/energy_h1_resume_recheck.json')
s=s.replace('Use the evaluated source archive if the current source tree has changed; current-source mismatch intentionally fails.',
 'The [read-only compatibility command](../../smart_building_conformal/scripts/read_matched_energy005.py) verifies and extracts the exact evaluated source archive, checks fresh data/config identities and forbids fitting. It applies the declared schema adapter only after confirming the original source group is Python None, and records its own reader hash separately. The newer production export repair requires a fresh source identity for future fits; direct current-source resume against the older frozen protocol intentionally fails. The [successful archive-based resume](../../smart_building_conformal/outputs/matched_forecasting005/validation/energy_h1_archive_resume_v1.json) confirms this public reproduction route also performs zero fits and leaves every run file unchanged.')
s += '\nThe initial group-identity audit failure is preserved in [energy_h1_audit_v1.log](../../smart_building_conformal/outputs/matched_forecasting005/validation/energy_h1_audit_v1.log). The repaired exporter passed [two additional no-fit checks](../../smart_building_conformal/outputs/matched_forecasting005/validation/identifier_export_v1.log). The numerical audit succeeded in v2; no real learned model was refitted. See [current source archive](current_source.zip) and [its source ledger](current_source_manifest.csv), separately from the evaluated source archive.\n'
p.write_bytes(s.encode('utf-8'))
