"""Rebuild and verify every Chapter 4 figure, then write the package inventory.

Runs each figure script in figure order, so every PNG, PDF and derived data
file in this folder is regenerated from the frozen sources and checked:
plotted values against the source tables, printed text size, text overlap,
the 15.0 cm text width and vector-only PDFs. It then confirms that Figures 4.1
to 4.9 are each present once, each has a caption and no two outputs are
byte-identical, and writes:

* CHAPTER4_FIGURE_INVENTORY.csv, one row per figure;
* CHAPTER4_FIGURE_INVENTORY.md, the same inventory for reading;
* CHAPTER4_FIGURE_CAPTIONS.md, the final caption text, taken from each figure
  script, with comparisons formatted from full-precision source values.

Nothing here trains a model or reruns an experiment.

Usage:
    python report_figures/chapter4/build_chapter4_figures.py
"""

from __future__ import annotations

import csv
import hashlib
import importlib
import re

import chapter4_style as c4

SCRIPTS = (
    "figure_4_1_point_forecasting_mae",
    "figure_4_2_4_3_interval_coverage_width",
    "figure_4_4_4_5_alert_tradeoffs",
    "figure_4_6_sensor_disturbance_coverage",
    "figure_4_7_recalibration_recovery",
    "figure_4_8_attention_lstm_cost_interval_quality",
    "figure_4_9_paired_conditional_detection_differences",
)
FIGURES = tuple(f"4.{number}" for number in range(1, 10))
INVENTORY_CSV = c4.OUT_DIR / "CHAPTER4_FIGURE_INVENTORY.csv"
INVENTORY_MD = c4.OUT_DIR / "CHAPTER4_FIGURE_INVENTORY.md"
CAPTIONS_MD = c4.OUT_DIR / "CHAPTER4_FIGURE_CAPTIONS.md"


def sha256(path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def figure_number(stem: str) -> str:
    return ".".join(re.match(r"figure_(\d+)_(\d+)_", stem).groups())


def collect() -> tuple[list[dict], dict[str, dict]]:
    records, captions = [], {}
    for script in SCRIPTS:
        start = len(c4.RESULTS)
        importlib.import_module(script).main()
        for result in c4.RESULTS[start:]:
            stem, layout = result["stem"], c4.LAYOUT[result["stem"]]
            png, pdf = c4.OUT_DIR / f"{stem}.png", c4.OUT_DIR / f"{stem}.pdf"
            data = [path for path in result["outputs"] if path.endswith(".csv")]
            records.append({
                "figure": figure_number(stem),
                "title": layout["title"].split(". ", 1)[1],
                "script": f"report_figures/chapter4/{script}.py",
                "png": c4.repo_relative(png),
                "pdf": c4.repo_relative(pdf),
                "data_csv": "; ".join(data),
                "sources": "; ".join(f"{s['source_path']} @ {s['source_commit'][:10]}" for s in result["sources"]),
                "plotted_values_verified": result["values"],
                "max_abs_difference": f"{result['max_difference']:.3g}",
                "source_checks": " | ".join(result["notes"]),
                "print_width_cm": f"{layout['print_cm'][0]:.2f}",
                "print_height_cm": f"{layout['print_cm'][1]:.2f}",
                "png_pixels": "x".join(str(count) for count in layout["png_pixels"]),
                "text_pt": f"{layout['min_text_pt']:g}-{layout['max_text_pt']:g}",
                "png_sha256": sha256(png),
                "pdf_sha256": sha256(pdf),
            })
            captions[records[-1]["figure"]] = {"caption": result["caption"], "accompanying": result["accompanying"]}
    return records, captions


def check_package(records: list[dict], captions: dict[str, dict]) -> None:
    numbers = [record["figure"] for record in records]
    if tuple(numbers) != FIGURES:
        raise AssertionError(f"expected Figures {', '.join(FIGURES)}, built {', '.join(numbers)}")
    missing = [number for number in numbers if not captions[number]["caption"].strip()]
    if missing:
        raise AssertionError(f"no caption for Figures {', '.join(missing)}")
    for kind in ("png_sha256", "pdf_sha256"):
        hashes = [record[kind] for record in records]
        if len(set(hashes)) != len(hashes):
            raise AssertionError(f"two figures share identical {kind[:3].upper()} content")


def write_inventory(records: list[dict]) -> None:
    with INVENTORY_CSV.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(records[0]), lineterminator="\n")
        writer.writeheader()
        writer.writerows(records)
    lines = [
        "# Chapter 4 figure inventory",
        "",
        "Generated by `build_chapter4_figures.py` from the frozen candidature evidence; no model was",
        "trained and no experiment rerun. Every figure is drawn at the 15.0 cm A4 text width of the",
        "UM thesis layout (left margin 4.0 cm, right 2.0 cm) and placed at 100%, so the text sizes",
        "below are printed sizes. PNGs are 300 dpi; PDFs are vector-only with embedded TrueType fonts.",
        "",
        "| Figure | Title | Files | Plotted values verified | Print size (cm) | Text (pt) |",
        "|---|---|---|---:|---|---|",
    ]
    for record in records:
        files = [record["png"], record["pdf"], *filter(None, record["data_csv"].split("; "))]
        names = "<br>".join(f"`{path.rsplit('/', 1)[1]}`" for path in files)
        lines.append(
            f"| {record['figure']} | {record['title']} | {names} | {record['plotted_values_verified']} "
            f"(max diff {record['max_abs_difference']}) | {record['print_width_cm']} x {record['print_height_cm']} "
            f"| {record['text_pt']} |"
        )
    lines += ["", "## Sources and checks", ""]
    for record in records:
        lines.append(f"**Figure {record['figure']}.** Script `{record['script'].rsplit('/', 1)[1]}`.")
        lines.append("")
        lines += [f"- Source: `{source}`" for source in record["sources"].split("; ")]
        lines += [f"- Checked: {note}" for note in filter(None, record["source_checks"].split(" | "))]
        lines.append(f"- SHA-256: PNG `{record['png_sha256'][:16]}`, PDF `{record['pdf_sha256'][:16]}`")
        lines.append("")
    INVENTORY_MD.write_text("\n".join(lines).rstrip("\n") + "\n", encoding="utf-8", newline="\n")


def write_captions(records: list[dict], captions: dict[str, dict]) -> None:
    lines = [
        "# Chapter 4 figure captions",
        "",
        "Final caption text for Figures 4.1 to 4.9, generated by `build_chapter4_figures.py` from the caption",
        "text kept in each figure script. Numbers in the Figure 4.6 text are formatted from full-precision",
        "source values when the figure is built.",
    ]
    for record in records:
        entry = captions[record["figure"]]
        lines += ["", f"## Figure {record['figure']}. {record['title']}", "", entry["caption"]]
        if entry["accompanying"]:
            lines += ["", "**Accompanying text.** " + entry["accompanying"]]
        files = [record["png"], record["pdf"], *filter(None, record["data_csv"].split("; "))]
        lines += ["", "Files: " + ", ".join(f"`{path.rsplit('/', 1)[1]}`" for path in files)]
    CAPTIONS_MD.write_text("\n".join(lines).rstrip("\n") + "\n", encoding="utf-8", newline="\n")


def main() -> None:
    records, captions = collect()
    check_package(records, captions)
    write_inventory(records)
    write_captions(records, captions)
    print(f"inventory: Figures {records[0]['figure']}-{records[-1]['figure']} built, verified, captioned and distinct")
    for path in (INVENTORY_CSV, INVENTORY_MD, CAPTIONS_MD):
        print(f"  wrote   {c4.repo_relative(path)}")


if __name__ == "__main__":
    main()
