"""No-fit inventory of actual method owners, callable endpoints and remaining gaps."""
import ast
from common import *

ROWS=[
 ('matched point/static absolute intervals','matched_forecasting005.py','main','available CLI: freeze/readiness/run/validate/resume','Persistence; selected XGBRegressor; AttentionLSTM','Both levels share one fitted point owner; these artifacts do not replace CQR/EnbPI owners'),
 ('quantile and CQR owner','conformal_cqr.py','fit_cqr','available Python function','MAPIE ConformalizedQuantileRegressor with three HistGradientBoostingRegressor quantile sub-estimators per level','Uncalibrated/CQR share the exact quantile owner and raw outputs'),
 ('uncalibrated quantile bounds','conformal_quantile.py','quantile_interval','available Python function','sub-estimators from the same CQR owner','No new predictor fit for uncalibrated ablation'),
 ('recentred EnbPI owner','interval_stream.py','IntervalEstimator','available Python class; not a matched-method matrix CLI','MAPIE TimeSeriesRegressor; XGBoost base, explicitly recorded RandomForest fallback','Current factory uses 60 trees and five 24-step block-bootstrap resamplings; do not substitute matched 400-tree owner or guess sub-fit counts'),
 ('causal residual pool','residuals.py','DelayedResidualPool','available Python class','same fitted predictor that emits the stream','Only target_time <= current origin is observable; isolate updates by original group/segment'),
 ('DSCP calibrator','conformal_dscp.py','fit_dscp','available Python function; joint-origin adapter required','Frozen amendment-005 matrix declares matched XGBoost predictions','Share learned direct-horizon XGBoost artifacts and DSCP calibration/assignment across levels when identities match; legacy StudyRunner uses CQR medians and is not this matrix'),
 ('seasonal baseline','baselines.py','seasonal_naive_prediction','available Python function; versioned matched matrix adapter required','deterministic target at forecast target minus one daily period','No learned fits; five seed aliases per unique horizon/fold; inapplicable inside four-hour RICO runs'),
 ('method-owned operational predictor','operational004_stream.py','OwnedInterval','available Python class','CQR/uncalibrated HistGBR; recentred EnbPI own base; persistence split','Share quantile owner and cache raw predictions by feature hash and fit identity'),
 ('causal sensor/input replay','operational004_stream.py','corrupted_features','available Python function','same owner receives causal corrupted feature rows','Inject observed target/missingness before lags; within-segment forward fill; never clean future observations'),
 ('method-preserving recalibration','operational004_stream.py','replay','available Python function','CQR nonconformity or signed EnbPI residuals; static methods retain owned bounds','Issue bounds, compare matured reading to those issued bounds, then release score; hold updates with insufficient support'),
 ('operational nested selection','operational004_metrics.py','select_pipeline','available Python function','both frozen inner folds, common candidate grid','Primary recall LCB >= .6 and workload UCB <= 1 per asset-day in each fold; unavailable bounds imply infeasibility and explicit abstention'),
 ('operational evaluation engine','operational004_engine.py','evaluate_unit','available Python function; full-grid authorized wrapper still required','OwnedInterval','Existing CLI uses reduced nine-candidate grid; full 264-candidate claim cannot reuse that label'),
 ('bounded operational CLI','operational004.py','run','available CLI: dataset/fold/seed/out/config/execution-manifest/resume','reduced-grid operational engine','Existing code retains a hard 3 GiB launch check; next wrapper must explicitly carry current nonblocking launch policy without weakening epoch/disk floors'),
]

def main():
    out=BATCH/'readiness_map_v1';out.mkdir(parents=True,exist_ok=False)
    rows=[]
    for scope,file,symbol,status,owner,sharing in ROWS:
        path=SMART/'src'/file;parsed=ast.parse(path.read_text(encoding='utf-8'))
        nodes=[n for n in parsed.body if isinstance(n,(ast.FunctionDef,ast.ClassDef)) and n.name==symbol]
        assert len(nodes)==1,(file,symbol)
        rows.append(dict(scope=scope,path=path.relative_to(ROOT).as_posix(),symbol=symbol,line=nodes[0].lineno,source_sha256=sha(path),actual_status=status,estimator_owner=owner,sharing_or_constraint=sharing))
    with (out/'entrypoints_and_owners.csv').open('w',newline='',encoding='utf-8') as f:
        w=csv.DictWriter(f,fieldnames=list(rows[0]));w.writeheader();w.writerows(rows)
    text='# Broader conformal-method and alert implementation readiness\n\nThis is a no-fitting inventory of the current code and existing amendment-005 execution plan. It does not redesign the protocol, authorize another experiment, or treat matched absolute-error intervals as completed CQR/EnbPI/DSCP evidence. [Machine-readable entrypoint/owner inventory](smart_building_conformal/outputs/matched_forecasting005/fold2_multiseed_batch_v1/readiness_map_v1/entrypoints_and_owners.csv) records source hashes and callable locations.\n\n'
    text+='| Component | Actual available endpoint | Owner and remaining adapter work |\n|---|---|---|\n'
    for r in rows:text+=f'| {r["scope"]} | [{r["symbol"]}]({r["path"]}#L{r["line"]}): {r["actual_status"]} | {r["estimator_owner"]}. {r["sharing_or_constraint"]}. |\n'
    text+='\nThe current scientific [method matrix](smart_building_conformal/outputs/amendment005/study_plan_v1/interval_method_matrix.csv) specifies 1,950 level/horizon cells. Its **DSCP owner is matched XGBoost**, whereas legacy `StudyRunner._run_dscp` uses CQR medians. Reusing the legacy driver unchanged would answer a different comparison. The new joint-origin adapter must use the declared matched XGBoost streams, intersect `(original group, origin_time)` across all declared horizons separately for calibration/test, and verify each horizon target and strict role boundary against the [frozen joint-origin support](smart_building_conformal/outputs/amendment005/support_final_checks_v1/dscp_joint_origin_support.csv). Clustering, merging and neighbour selection consume only calibration predictions/errors. Test sequences may be assigned to the frozen calibrator; test errors cannot train it.\n\n'
    text+='## Smallest next executable implementation package\n\nImplement a new versioned `src.matched_intervals005` adapter with freeze/readiness/run/validate/resume, consuming the existing interval-method matrix and exact matched roles. Keep the matched forecasting runner and its completed artifacts unchanged. The package should first pass a bounded synthetic owner/checkpoint/causal-replay integration fixture, then expose one separately authorized real-data proposal: **BDG2 fold 2 / seed 42 / horizons 1,3,6 / both levels / all five declared interval methods**, plus clean-stream alert-consumption verification. No such fitting or calibrator training is launched in this task.\n\n'
    text+='1. Persist a shared-owner registry keyed by task/horizon/fold/seed, role/input/config hash and quantile level where relevant. CQR and uncalibrated quantiles share one quantile object; static/updated EnbPI share the same trained ensemble. Sharing levels is allowed only when the owner/calibration contract is identical. Record every actual base/sub-estimator fit, identity, fallback and measured cost; do not label one MAPIE wrapper as one base-learner fit. Serialize owners and independently reload predictions.\n'
    text+='2. Reuse completed matched XGBoost direct-horizon artifacts for the declared DSCP owner. Add the exact joint-origin join and serialized DSCP state, preserving the direct-horizon adaptation label. Cache assignments across levels; measure clustering and neighbour costs separately. Add seasonal prediction export on the same targets as a deterministic adapter; RICO daily seasonality remains inapplicable. These are distinct cells, not substitutions for existing model rows.\n'
    text+='3. Export one method-owned row stream with row/group/origin/target IDs, owner identity, point/raw/static/issued bounds, observation availability, released-score times and update status. Connect it to amendment-004 `replay` and `alert_on_stream` without passing CQR through the legacy generic signed-residual wrapper. Check causal corruption before feature construction, matured-observation scoring before score release, independent original-group updates, and explicit historical calibration initialization for a new run.\n'
    text+='4. Exercise two original groups, horizon > 1, delayed outcomes, CQR nonconformity versus EnbPI signed scores, static bounds, missing observations, unsupported update ranks, crossing-order handling, zero-control alias equality, corrupted checkpoints and zero-fit resume. Independently recalculate coverage/MPIW/Winkler and reconcile emitted/consumed stream hashes. The real BDG2 proposal follows these checks and fresh authorization/freeze/readiness; do not invent an executable CLI before implementation exists.\n\n'
    text+='The historical `scripts/check_remaining_study005.py` still asserts that the matched forecasting module does not exist; its old checker cannot validate the now-implemented runner. Its preserved outputs remain historical evidence. Current no-fit checks are the `src.matched_forecasting005 readiness` action with explicit matrix/key/design and a fresh receipt, the new 52-unit preflight, and this source-symbol inventory. The proposed `src.matched_intervals005` adapter is **not currently available**. Existing `src.operational004 --help` documents a reduced-grid operational CLI, not a full-method matched driver. No command in this inventory is a fitting authorization.\n\n'
    text+='## Supported endpoints and remaining evidence\n\nMatched point/interval/compute comparisons are supported for all four tasks with frozen memberships. The current task completes only fold-2 training-seed replication; the cumulative report/queue gives exact remaining outer-fold cells. Seasonal evidence requires 27 unique deterministic horizon/fold computations, five aliases each, on PLEIA temperature/energy and BDG2. RICO has no daily cycle within an independent four-hour acquisition run.\n\n'
    text+='Amendment-004 primary operational feasibility remains supported for evaluation on BDG2; its completed reduced-grid results include explicit abstentions. A full-grid 264-candidate, five-model-seed operational claim still requires its own versioned execution wrapper and authorization. PLEIA temperature, PLEIA energy and RICO remain unsupported for the original primary selection under the frozen exposure/event/original-unit minima. Preserve those null/abstention endpoints. Amendment-005 C contexts are a separate conditional-challenge question and have support tables, but no completed context-replay endpoint that can replace primary deployment feasibility. Do not lower thresholds or replace unavailable bounds with point estimates.\n\n'
    text+='Keep both required inner folds, recall LCB >= 0.6 and workload UCB <= 1 episode/asset-day, fixed catalogue seeds/strata, current tie rules and explicit no-feasible-configuration behavior. Preserve the remaining 900 legacy robustness/contamination/recovery cells as obligations requiring the amendment-005 crosswalk: zero controls, calibration-only contamination, closed-loop causal features and released scores, cascades, original-unit contributions, restricted recovery time and censoring. No unseen-building portability or conditional population-coverage claim is supported by this fold-2 slice. Full-study readiness remains false.\n'
    atomic(ROOT/'MATCHED_METHOD_READINESS_MAP.md',text)
    atomic(out/'validation.json',dict(passed=True,models_fitted=0,verified_symbols=len(rows),matched_interval_cli_exists=(SMART/'src/matched_intervals005.py').exists(),dscp_matrix_owner='matched XGBoost',legacy_dscp_owner='CQR median',next_real_data_proposal_authorized=False))
    atomic(out/'COMPLETE.json',dict(files=tree(out),models_fitted=0));print('Inventory verified:',len(rows),'entrypoints; no fitting')

if __name__=='__main__':main()
